{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    colmena.url = "github:zhaofengli/colmena";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    simple-nixos-mailserver = {
      url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-minecraft = {
      url = "github:Infinidoge/nix-minecraft";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-server = {
      url = "github:versia-pub/server";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-fe = {
      url = "github:versia-pub/frontend";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    disko,
    sops-nix,
    simple-nixos-mailserver,
    versia-server,
    home-manager,
    nix-minecraft,
    versia-fe,
    colmena,
    ...
  } @ inputs: let
    # Generated by Terraform: public and private addresses of each host
    hosts = builtins.fromJSON (builtins.readFile ./terraform/nixos-vars.json);
    infra = {
      inherit hosts;
      # Private network addresses, used for inter-host traffic
      ips = builtins.mapAttrs (name: host: host.network_ipv4) hosts;
    };

    forAllSystems = f:
      nixpkgs.lib.genAttrs ["x86_64-linux" "aarch64-linux" "aarch64-darwin"] (
        system: f system nixpkgs.legacyPackages.${system}
      );
  in {
    colmenaHive = colmena.lib.makeHive {
      meta = {
        nixpkgs = import nixpkgs {
          system = "x86_64-linux";
          overlays = [
            nix-minecraft.overlay
            versia-server.overlays.default
            versia-fe.overlays.default
          ];
        };

        specialArgs = {inherit inputs infra;};
      };

      defaults = {name, ...}: {
        deployment = {
          targetHost = "${name}.infra.cpluspatch.com";
          tags = ["infra"];
        };

        networking.hostName = name;

        imports = [
          disko.nixosModules.disko
          sops-nix.nixosModules.sops
          home-manager.nixosModules.home-manager
          ./nix/hosts/base
          ./nix/features/partitions/single-zfs.nix
        ];
      };

      faithplate.imports = [
        simple-nixos-mailserver.nixosModules.default
        nix-minecraft.nixosModules.minecraft-servers
        versia-server.nixosModules.versia-server
        ./nix/hosts/faithplate
      ];

      freeman.imports = [
        ./nix/hosts/freeman
      ];

      eli.imports = [
        nix-minecraft.nixosModules.minecraft-servers
        ./nix/hosts/eli
      ];
    };

    # Builds every host's system closure, e.g. with `nix flake check`
    checks.x86_64-linux = self.colmenaHive.toplevel;

    devShells = forAllSystems (system: pkgs: {
      default = pkgs.mkShell {
        buildInputs = [
          colmena.packages.${system}.colmena
          pkgs.alejandra
          pkgs.nixd
          pkgs.sops
        ];
      };
    });

    formatter = forAllSystems (system: pkgs: pkgs.alejandra);
  };
}
