{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    colmena.url = "github:zhaofengli/colmena";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    simple-nixos-mailserver = {
      url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-minecraft = {
      url = "github:Infinidoge/nix-minecraft";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-server = {
      url = "github:versia-pub/server";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-fe = {
      url = "github:versia-pub/frontend";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    disko,
    sops-nix,
    simple-nixos-mailserver,
    versia-server,
    nix-minecraft,
    versia-fe,
    colmena,
    ...
  } @ inputs: let
    # Generated by Terraform: public and private addresses of each host
    hosts = builtins.fromJSON (builtins.readFile ./terraform/nixos-vars.json);
    infra = {
      inherit hosts;
      # Private network addresses, used for inter-host traffic
      ips = builtins.mapAttrs (name: host: host.network_ipv4) hosts;
    };

    forAllSystems = f:
      nixpkgs.lib.genAttrs ["x86_64-linux" "aarch64-linux" "aarch64-darwin"] (
        system: f system nixpkgs.legacyPackages.${system}
      );
  in {
    colmenaHive = colmena.lib.makeHive {
      meta = {
        nixpkgs = import nixpkgs {
          system = "x86_64-linux";
          overlays = [
            nix-minecraft.overlay
            versia-server.overlays.default
            versia-fe.overlays.default
          ];
        };

        specialArgs = {inherit inputs infra;};
      };

      defaults = {name, ...}: {
        deployment = {
          targetHost = "${name}.infra.cpluspatch.com";
          tags = ["infra"];
        };

        networking.hostName = name;

        imports = [
          disko.nixosModules.disko
          sops-nix.nixosModules.sops
          ./nix/hosts/base
          ./nix/features/partitions/single-zfs.nix
        ];
      };

      faithplate.imports = [
        simple-nixos-mailserver.nixosModules.default
        nix-minecraft.nixosModules.minecraft-servers
        versia-server.nixosModules.versia-server
        ./nix/hosts/faithplate
      ];

      freeman.imports = [
        ./nix/hosts/freeman
      ];

      eli.imports = [
        nix-minecraft.nixosModules.minecraft-servers
        ./nix/hosts/eli
      ];
    };

    # Domains pointing to each host, read by Terraform from terraform/domains.json.
    # Regenerate with: nix eval --json .#domains | jq -S . > terraform/domains.json
    domains = nixpkgs.lib.filterAttrs (host: domains: domains != []) (
      builtins.mapAttrs (host: node: nixpkgs.lib.sort nixpkgs.lib.lessThan (nixpkgs.lib.unique node.config.modules.dns.domains)) self.colmenaHive.nodes
    );

    checks.x86_64-linux =
      # Builds every host's system closure, e.g. with `nix flake check`
      self.colmenaHive.toplevel
      // {
        domains = let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
        in
          pkgs.runCommand "check-terraform-domains" {nativeBuildInputs = [pkgs.jq];} ''
            if ! diff <(jq -S . ${pkgs.writeText "domains.json" (builtins.toJSON self.domains)}) <(jq -S . ${./terraform/domains.json}); then
              echo "terraform/domains.json is outdated, regenerate it (see flake.nix)" >&2
              exit 1
            fi
            touch $out
          '';

        secrets = let
          pkgs = nixpkgs.legacyPackages.x86_64-linux;
          src = nixpkgs.lib.fileset.toSource {
            root = ./.;
            fileset = nixpkgs.lib.fileset.unions [./.sops.yaml ./secrets];
          };
        in
          pkgs.runCommand "check-secrets" {nativeBuildInputs = [pkgs.bash pkgs.jq pkgs.yq-go];} ''
            bash ${./scripts/check-secrets.sh} ${pkgs.writeText "registry.json" (builtins.toJSON (import ./secrets/registry.nix))} ${src}
            touch $out
          '';
      };

    devShells = forAllSystems (system: pkgs: {
      default = pkgs.mkShell {
        buildInputs = [
          colmena.packages.${system}.colmena
          pkgs.alejandra
          pkgs.nixd
          pkgs.sops
          pkgs.ssh-to-age
        ];
      };
    });

    formatter = forAllSystems (system: pkgs: pkgs.alejandra);
  };
}
