{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    lix = {
      url = "https://git.lix.systems/lix-project/lix/archive/main.tar.gz";
      flake = false;
    };
    lix-module = {
      url = "https://git.lix.systems/lix-project/nixos-module/archive/main.tar.gz";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.lix.follows = "lix";
    };
    colmena.url = "github:zhaofengli/colmena";
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    simple-nixos-mailserver = {
      url = "gitlab:simple-nixos-mailserver/nixos-mailserver";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-minecraft = {
      url = "github:Infinidoge/nix-minecraft";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-server = {
      url = "github:versia-pub/server";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    versia-fe = {
      url = "github:versia-pub/frontend";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    lix-module,
    disko,
    sops-nix,
    simple-nixos-mailserver,
    versia-server,
    home-manager,
    nix-minecraft,
    versia-fe,
    colmena,
    ...
  } @ inputs: let
    # Generated by Terraform: public and private addresses of each host
    hosts = builtins.fromJSON (builtins.readFile ./terraform/nixos-vars.json);
    infra = {
      inherit hosts;
      # Private network addresses, used for inter-host traffic
      ips = builtins.mapAttrs (name: host: host.network_ipv4) hosts;
    };
  in {
    colmenaHive = colmena.lib.makeHive {
      meta = {
        nixpkgs = import nixpkgs {
          system = "x86_64-linux";
          overlays = [
            nix-minecraft.overlay
            versia-server.overlays.default
            versia-fe.overlays.default
          ];
        };

        specialArgs = {inherit inputs infra;};
      };

      defaults = {name, ...}: {
        deployment = {
          targetHost = "${name}.infra.cpluspatch.com";
          tags = ["infra"];
        };

        networking.hostName = name;

        imports = [
          lix-module.nixosModules.lixFromNixpkgs
          disko.nixosModules.disko
          sops-nix.nixosModules.sops
          home-manager.nixosModules.home-manager
          ./nix/hosts/base
          ./nix/features/partitions/single-zfs.nix
        ];
      };

      faithplate.imports = [
        simple-nixos-mailserver.nixosModules.default
        nix-minecraft.nixosModules.minecraft-servers
        versia-server.nixosModules.versia-server
        ./nix/hosts/faithplate
      ];

      freeman.imports = [
        ./nix/hosts/freeman
      ];

      eli.imports = [
        nix-minecraft.nixosModules.minecraft-servers
        ./nix/hosts/eli
      ];
    };

    devShells =
      builtins.mapAttrs (system: pkgs: {
        default = pkgs.mkShell {
          buildInputs = [
            colmena.packages.x86_64-linux.colmena
            pkgs.nixd
            pkgs.sops
          ];
        };
      })
      nixpkgs.legacyPackages;
  };
}
