# Hetzner Cloud networking, using the addresses generated by Terraform:
# static public addresses on enp1s0, DHCP on the private network (enp7s0)
{
  config,
  lib,
  infra,
  ...
}: let
  host = infra.hosts.${config.networking.hostName};
  # Hosts without a public IPv4 address are IPv6-only
  hasIpv4 = host.ipv4 != "";
in {
  networking = {
    useNetworkd = true;
    useDHCP = false;

    # Hetzner recursive resolvers
    nameservers =
      lib.optionals hasIpv4 [
        "185.12.64.1"
        "185.12.64.2"
      ]
      ++ [
        "2a01:4ff:ff00::add:1"
        "2a01:4ff:ff00::add:2"
      ];

    # Trust the LAN interface
    firewall.trustedInterfaces = ["enp7s0"];
  };

  # BBR keeps throughput up on long or lossy paths (backups to Fastly and kleiner, federation)
  # where cubic backs off at every lost packet. fq is the queueing it's designed for
  boot.kernelModules = ["tcp_bbr"];
  boot.kernel.sysctl = {
    "net.ipv4.tcp_congestion_control" = "bbr";
    "net.core.default_qdisc" = "fq";
  };

  systemd.network = {
    enable = true;

    # Don't block boot on every interface being configured
    wait-online.anyInterface = true;

    networks."30-wan" = {
      matchConfig.Name = "enp1s0";
      networkConfig.DHCP = "no";
      address =
        lib.optional hasIpv4 "${host.ipv4}/32"
        ++ ["${host.ipv6}/64"];
      routes =
        lib.optional hasIpv4 {
          Gateway = "172.31.1.1";
          GatewayOnLink = true;
        }
        ++ [{Gateway = "fe80::1";}];
    };

    networks."31-lan" = {
      matchConfig.Name = "enp7s0";
      networkConfig.DHCP = "ipv4";
    };
  };
}
